library(devtools)
install_github("slidify","ramnathv")
install_github("slidifyLibraries","ramnathv")
library(slidify)
library(slidifyLibraries)
library(rmarkdown)
library(knitr)

#author("1 - Intro to R")
#author("2 - Subsetting")
#author("3 - Control structures")
#author("4 - User-written functions")
#author("5 - Built-in functions")
#author("6 - Data manipulation") 
#author("6 - Exercises data manipulation")
author("7 - Plotting")
